package com.example.kang.player.redux

/**
 * Created by kang on 17-3-16.
 */
object Actions {
    val ACTION_PREVIOUS_SONG = "ACTION_PREVIOUS_SONG"
    val ACTION_NEXT_SONG = "ACTION_NEXT_SONG"
    val ACTION_PAUSE_SONG = "ACTION_PAUSE_SONG"
    val ACTION_PLAY_SONG = "ACTION_PLAY_SONG"
    val ACTION_SEEK_SONG = "ACTION_SEEK_SONG"
    val ACTION_UPDATE_PLAY_STATE_INFO = "ACTION_UPDATE_PLAY_STATE_INFO"
    val ACTION_UPDATE_SONG_INFO = "ACTION_UPDATE_SONG_INFO"
}
